// Gallery data - Black & White Photography Collection
const galleryData = [
    { id: 1, src: 'images/gallery/aves.jpg', title: 'Aves', category: 'black-white' },
    { id: 2, src: 'images/gallery/Bicycle on floor.jpg', title: 'Bicycle on Floor', category: 'black-white' },
    { id: 3, src: 'images/gallery/BirdWater.jpg', title: 'Bird Water', category: 'black-white' },
    { id: 4, src: 'images/gallery/boy.jpg', title: 'Boy', category: 'black-white' },
    { id: 5, src: 'images/gallery/branches.jpg', title: 'Branches', category: 'black-white' },
    { id: 6, src: 'images/gallery/Bus Lane.jpg', title: 'Bus Lane', category: 'black-white' },
    { id: 7, src: 'images/gallery/campanas.jpg', title: 'Campanas', category: 'black-white' },
    { id: 8, src: 'images/gallery/cartucho.jpg', title: 'Cartucho', category: 'black-white' },
    { id: 9, src: 'images/gallery/Center of Attention.jpg', title: 'Center of Attention', category: 'black-white' },
    { id: 10, src: 'images/gallery/centinel bird.jpg', title: 'Centinel Bird', category: 'black-white' },
    { id: 11, src: 'images/gallery/Chimney.jpg', title: 'Chimney', category: 'black-white' },
    { id: 12, src: 'images/gallery/Close Dance.jpg', title: 'Close Dance', category: 'black-white' },
    { id: 13, src: 'images/gallery/cuadros.jpg', title: 'Cuadros', category: 'black-white' },
    { id: 14, src: 'images/gallery/DenHaag Solitude.jpg', title: 'DenHaag Solitude', category: 'black-white' },
    { id: 15, src: 'images/gallery/DESCANSO HDR.jpg', title: 'Descanso HDR', category: 'black-white' },
    { id: 16, src: 'images/gallery/DonJuan.jpg', title: 'Don Juan', category: 'black-white' },
    { id: 17, src: 'images/gallery/Dove Liberty.jpg', title: 'Dove Liberty', category: 'black-white' },
    { id: 18, src: 'images/gallery/Dryl eaves.jpg', title: 'Dry Leaves', category: 'black-white' },
    { id: 19, src: 'images/gallery/dryleave.jpg', title: 'Dry Leave', category: 'black-white' },
    { id: 20, src: 'images/gallery/dulce descanso.jpg', title: 'Dulce Descanso', category: 'black-white' },
    { id: 21, src: 'images/gallery/ElMorroClouds.jpg', title: 'El Morro Clouds', category: 'black-white' },
    { id: 22, src: 'images/gallery/EquusMentis.jpg', title: 'Equus Mentis', category: 'black-white' },
    { id: 23, src: 'images/gallery/Esperando.jpg', title: 'Esperando', category: 'black-white' },
    { id: 24, src: 'images/gallery/Facing Trees.jpg', title: 'Facing Trees', category: 'black-white' },
    { id: 25, src: 'images/gallery/Flatiron.jpg', title: 'Flatiron', category: 'black-white' },
    { id: 26, src: 'images/gallery/gargola.jpg', title: 'Gárgola', category: 'black-white' },
    { id: 27, src: 'images/gallery/Gaudi.jpg', title: 'Gaudí', category: 'black-white' },
    { id: 28, src: 'images/gallery/Gracias a la Vida!!!.jpg', title: 'Gracias a la Vida', category: 'black-white' },
    { id: 29, src: 'images/gallery/Happy.jpg', title: 'Happy', category: 'black-white' },
    { id: 30, src: 'images/gallery/hojas.jpg', title: 'Hojas', category: 'black-white' },
    { id: 31, src: 'images/gallery/HomenajeAlCreador-Edit.jpg', title: 'Homenaje Al Creador', category: 'black-white' },
    { id: 32, src: 'images/gallery/Icepick.jpg', title: 'Icepick', category: 'black-white' },
    { id: 33, src: 'images/gallery/Inquisition.jpg', title: 'Inquisition', category: 'black-white' },
    { id: 34, src: 'images/gallery/LasDoradasCholuteca.jpg', title: 'Las Doradas Choluteca', category: 'black-white' },
    { id: 35, src: 'images/gallery/Leaves Wall.jpg', title: 'Leaves Wall', category: 'black-white' },
    { id: 36, src: 'images/gallery/LibertyBack.jpg', title: 'Liberty Back', category: 'black-white' },
    { id: 37, src: 'images/gallery/Looking Up.jpg', title: 'Looking Up', category: 'black-white' },
    { id: 38, src: 'images/gallery/Lunch Time.jpg', title: 'Lunch Time', category: 'black-white' },
    { id: 39, src: 'images/gallery/manos heridas.jpg', title: 'Manos Heridas', category: 'black-white' },
    { id: 40, src: 'images/gallery/Natural Prison.jpg', title: 'Natural Prison', category: 'black-white' },
    { id: 41, src: 'images/gallery/Niño.jpg', title: 'Niño', category: 'black-white' },
    { id: 42, src: 'images/gallery/Old Claws.jpg', title: 'Old Claws', category: 'black-white' },
    { id: 43, src: 'images/gallery/pachi.jpg', title: 'Pachi', category: 'black-white' },
    { id: 44, src: 'images/gallery/Peacescape.jpg', title: 'Peacescape', category: 'black-white' },
    { id: 45, src: 'images/gallery/Peeking.jpg', title: 'Peeking', category: 'black-white' },
    { id: 46, src: 'images/gallery/pump.jpg', title: 'Pump', category: 'black-white' },
    { id: 47, src: 'images/gallery/Reading.jpg', title: 'Reading', category: 'black-white' },
    { id: 48, src: 'images/gallery/Reflection.jpg', title: 'Reflection', category: 'black-white' },
    { id: 49, src: 'images/gallery/rock boat.jpg', title: 'Rock Boat', category: 'black-white' },
    { id: 50, src: 'images/gallery/swisslux.jpg', title: 'Swisslux', category: 'black-white' },
    { id: 51, src: 'images/gallery/Take Off.jpg', title: 'Take Off', category: 'black-white' },
    { id: 52, src: 'images/gallery/techo.jpg', title: 'Techo', category: 'black-white' },
    { id: 53, src: 'images/gallery/The Eggman.jpg', title: 'The Eggman', category: 'black-white' },
    { id: 54, src: 'images/gallery/The Laundrywoman.jpg', title: 'The Laundrywoman', category: 'black-white' },
    { id: 55, src: 'images/gallery/Tower.jpg', title: 'Tower', category: 'black-white' },
    { id: 56, src: 'images/gallery/Trees.jpg', title: 'Trees', category: 'black-white' },
    { id: 57, src: 'images/gallery/UrbanParadox.jpg', title: 'Urban Paradox', category: 'black-white' },
    { id: 58, src: 'images/gallery/Waiving.jpg', title: 'Waiving', category: 'black-white' },
    { id: 59, src: 'images/gallery/wall light.jpg', title: 'Wall Light', category: 'black-white' },
    { id: 60, src: 'images/gallery/waterfall.jpg', title: 'Waterfall', category: 'black-white' },
    { id: 61, src: 'images/gallery/Wet Leaves.jpg', title: 'Wet Leaves', category: 'black-white' },
    { id: 62, src: 'images/gallery/Wet Sun.jpg', title: 'Wet Sun', category: 'black-white' },
    { id: 63, src: 'images/gallery/Windows Shadows.jpg', title: 'Windows Shadows', category: 'black-white' },
    { id: 64, src: 'images/gallery/Worker.jpg', title: 'Worker', category: 'black-white' }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { galleryData };
}
