// Color Photography Gallery Data
const colorGalleryData = [
    { id: 1, src: 'images/gallery/color/Afternoon Delight.jpg', title: 'Afternoon Delight', category: 'color' },
    { id: 2, src: 'images/gallery/color/Al Maqta\'s Centinel.jpg', title: 'Al Maqta\'s Centinel', category: 'color' },
    { id: 3, src: 'images/gallery/color/AnchoRed.jpg', title: 'AnchoRed', category: 'color' },
    { id: 4, src: 'images/gallery/color/chinmney leaves.jpg', title: 'Chimney Leaves', category: 'color' },
    { id: 5, src: 'images/gallery/color/Dutch Master.jpg', title: 'Dutch Master', category: 'color' },
    { id: 6, src: 'images/gallery/color/ElMorro-Edit.jpg', title: 'El Morro', category: 'color' },
    { id: 7, src: 'images/gallery/color/Equilibrium.jpg', title: 'Equilibrium', category: 'color' },
    { id: 8, src: 'images/gallery/color/fence.jpg', title: 'Fence', category: 'color' },
    { id: 9, src: 'images/gallery/color/FiveDomes.jpg', title: 'Five Domes', category: 'color' },
    { id: 10, src: 'images/gallery/color/flying.jpg', title: 'Flying', category: 'color' },
    { id: 11, src: 'images/gallery/color/friendly colors.jpg', title: 'Friendly Colors', category: 'color' },
    { id: 12, src: 'images/gallery/color/Full Circle.jpg', title: 'Full Circle', category: 'color' },
    { id: 13, src: 'images/gallery/color/Golden Moment.jpg', title: 'Golden Moment', category: 'color' },
    { id: 14, src: 'images/gallery/color/golden path.jpg', title: 'Golden Path', category: 'color' },
    { id: 15, src: 'images/gallery/color/GoldenPeace.jpg', title: 'Golden Peace', category: 'color' },
    { id: 16, src: 'images/gallery/color/green Leave2.jpg', title: 'Green Leaves', category: 'color' },
    { id: 17, src: 'images/gallery/color/Hanging Around.jpg', title: 'Hanging Around', category: 'color' },
    { id: 18, src: 'images/gallery/color/Hidden Beauty.jpg', title: 'Hidden Beauty', category: 'color' },
    { id: 19, src: 'images/gallery/color/hidden treasure.jpg', title: 'Hidden Treasure', category: 'color' },
    { id: 20, src: 'images/gallery/color/IFO.jpg', title: 'IFO', category: 'color' },
    { id: 21, src: 'images/gallery/color/iglesia2-Edit-Edit.jpg', title: 'Iglesia', category: 'color' },
    { id: 22, src: 'images/gallery/color/Inner Peace.jpg', title: 'Inner Peace', category: 'color' },
    { id: 23, src: 'images/gallery/color/Late Round.jpg', title: 'Late Round', category: 'color' },
    { id: 24, src: 'images/gallery/color/Lawn Shadow.jpg', title: 'Lawn Shadow', category: 'color' },
    { id: 25, src: 'images/gallery/color/Lineadura.jpg', title: 'Lineadura', category: 'color' },
    { id: 26, src: 'images/gallery/color/Lonely Planet.jpg', title: 'Lonely Planet', category: 'color' },
    { id: 27, src: 'images/gallery/color/Memento.jpg', title: 'Memento', category: 'color' },
    { id: 28, src: 'images/gallery/color/Morning Eye.jpg', title: 'Morning Eye', category: 'color' },
    { id: 29, src: 'images/gallery/color/Net.jpg', title: 'Net', category: 'color' },
    { id: 30, src: 'images/gallery/color/Number Four.jpg', title: 'Number Four', category: 'color' },
    { id: 31, src: 'images/gallery/color/One more time2.jpg', title: 'One More Time', category: 'color' },
    { id: 32, src: 'images/gallery/color/Pencil.jpg', title: 'Pencil', category: 'color' },
    { id: 33, src: 'images/gallery/color/Perfect Summer.jpg', title: 'Perfect Summer', category: 'color' },
    { id: 34, src: 'images/gallery/color/Postcard.jpg', title: 'Postcard', category: 'color' },
    { id: 35, src: 'images/gallery/color/Renaissance.jpg', title: 'Renaissance', category: 'color' },
    { id: 36, src: 'images/gallery/color/sailors.jpg', title: 'Sailors', category: 'color' },
    { id: 37, src: 'images/gallery/color/Shy.jpg', title: 'Shy', category: 'color' },
    { id: 38, src: 'images/gallery/color/sidewalk.jpg', title: 'Sidewalk', category: 'color' },
    { id: 39, src: 'images/gallery/color/sol.jpg', title: 'Sol', category: 'color' },
    { id: 40, src: 'images/gallery/color/soli.jpg', title: 'Soli', category: 'color' },
    { id: 41, src: 'images/gallery/color/Split Second.jpg', title: 'Split Second', category: 'color' },
    { id: 42, src: 'images/gallery/color/stairs.jpg', title: 'Stairs', category: 'color' },
    { id: 43, src: 'images/gallery/color/Standing Tall copy.jpg', title: 'Standing Tall', category: 'color' },
    { id: 44, src: 'images/gallery/color/Street Cup.jpg', title: 'Street Cup', category: 'color' },
    { id: 45, src: 'images/gallery/color/Sunset Composition.jpg', title: 'Sunset Composition', category: 'color' },
    { id: 46, src: 'images/gallery/color/Twins.jpg', title: 'Twins', category: 'color' },
    { id: 47, src: 'images/gallery/color/umbrellas.jpg', title: 'Umbrellas', category: 'color' },
    { id: 48, src: 'images/gallery/color/Visitor.jpg', title: 'Visitor', category: 'color' },
    { id: 49, src: 'images/gallery/color/warning.jpg', title: 'Warning', category: 'color' },
    { id: 50, src: 'images/gallery/color/white fabric.jpg', title: 'White Fabric', category: 'color' },
    { id: 51, src: 'images/gallery/color/whitevision.jpg', title: 'White Vision', category: 'color' },
    { id: 52, src: 'images/gallery/color/Wide Web.jpg', title: 'Wide Web', category: 'color' }
];
