// Street Photography Gallery Data
const streetGalleryData = [
    { id: 1, src: 'images/gallery/street/bikes.jpg', title: 'Bikes', category: 'street' },
    { id: 2, src: 'images/gallery/street/Calling.jpg', title: 'Calling', category: 'street' },
    { id: 3, src: 'images/gallery/street/cenital.jpg', title: 'Cenital', category: 'street' },
    { id: 4, src: 'images/gallery/street/corpeños.jpg', title: 'Corpeños', category: 'street' },
    { id: 5, src: 'images/gallery/street/cows.jpg', title: 'Cows', category: 'street' },
    { id: 6, src: 'images/gallery/street/crossing.jpg', title: 'Crossing', category: 'street' },
    { id: 7, src: 'images/gallery/street/Dog Vendor.jpg', title: 'Dog Vendor', category: 'street' },
    { id: 8, src: 'images/gallery/street/Dreamer.jpg', title: 'Dreamer', category: 'street' },
    { id: 9, src: 'images/gallery/street/emirati.jpg', title: 'Emirati', category: 'street' },
    { id: 10, src: 'images/gallery/street/Fading.jpg', title: 'Fading', category: 'street' },
    { id: 11, src: 'images/gallery/street/Hardship.jpg', title: 'Hardship', category: 'street' },
    { id: 12, src: 'images/gallery/street/in line.jpg', title: 'In Line', category: 'street' },
    { id: 13, src: 'images/gallery/street/Lady Eggs.jpg', title: 'Lady Eggs', category: 'street' },
    { id: 14, src: 'images/gallery/street/Manequins.jpg', title: 'Mannequins', category: 'street' },
    { id: 15, src: 'images/gallery/street/Meeting.jpg', title: 'Meeting', category: 'street' },
    { id: 16, src: 'images/gallery/street/moving.jpg', title: 'Moving', category: 'street' },
    { id: 17, src: 'images/gallery/street/mules.jpg', title: 'Mules', category: 'street' },
    { id: 18, src: 'images/gallery/street/Nun.jpg', title: 'Nun', category: 'street' },
    { id: 19, src: 'images/gallery/street/Ojojona.jpg', title: 'Ojojona', category: 'street' },
    { id: 20, src: 'images/gallery/street/Old Lady Door.jpg', title: 'Old Lady Door', category: 'street' },
    { id: 21, src: 'images/gallery/street/Old man Door.jpg', title: 'Old Man Door', category: 'street' },
    { id: 22, src: 'images/gallery/street/Pot Seller.jpg', title: 'Pot Seller', category: 'street' },
    { id: 23, src: 'images/gallery/street/Red Vendors.jpg', title: 'Red Vendors', category: 'street' },
    { id: 24, src: 'images/gallery/street/sign.jpg', title: 'Sign', category: 'street' },
    { id: 25, src: 'images/gallery/street/smoker.jpg', title: 'Smoker', category: 'street' },
    { id: 26, src: 'images/gallery/street/Station.jpg', title: 'Station', category: 'street' },
    { id: 27, src: 'images/gallery/street/street cat.jpg', title: 'Street Cat', category: 'street' },
    { id: 28, src: 'images/gallery/street/street life.jpg', title: 'Street Life', category: 'street' },
    { id: 29, src: 'images/gallery/street/sweeper.jpg', title: 'Sweeper', category: 'street' },
    { id: 30, src: 'images/gallery/street/the kiss.jpg', title: 'The Kiss', category: 'street' },
    { id: 31, src: 'images/gallery/street/The Loneliness of Poverty.jpg', title: 'The Loneliness of Poverty', category: 'street' },
    { id: 32, src: 'images/gallery/street/The Passenger.jpg', title: 'The Passenger', category: 'street' },
    { id: 33, src: 'images/gallery/street/The Tree of Life.jpg', title: 'The Tree of Life', category: 'street' },
    { id: 34, src: 'images/gallery/street/TimesSquare.jpg', title: 'Times Square', category: 'street' },
    { id: 35, src: 'images/gallery/street/Trio.jpg', title: 'Trio', category: 'street' },
    { id: 36, src: 'images/gallery/street/Up.jpg', title: 'Up', category: 'street' },
    { id: 37, src: 'images/gallery/street/Urban Calm B&W.jpg', title: 'Urban Calm B&W', category: 'street' },
    { id: 38, src: 'images/gallery/street/Urban Calm.jpg', title: 'Urban Calm', category: 'street' },
    { id: 39, src: 'images/gallery/street/Walkers.jpg', title: 'Walkers', category: 'street' },
    { id: 40, src: 'images/gallery/street/WashingtonSquare.jpg', title: 'Washington Square', category: 'street' }
];
